
import React, {useRef, useEffect, useState} from 'react'; 
import PieChart from "./PieChartFunctional.jsx";
import InputPieChart from "./InputPieChart.jsx";



function Revenue(props) { 

  const nextPageCallback = props.pageCallback;
  const updateChart = props.updateCallback;   
  let userRevenueData = [...props.data]

  let toolTipRevenue = {
    medicalCenterData : 'A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare.', 
    studentFeesData : 'Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc.',
    californiaData : 'General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services.',
    tuitionData : 'Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds.',
    researchData : 'Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research.',
    pellGrantData : 'Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it is 34%; at Cal Tech it is 14%; at Sac State it is 71%.',
    noneduData : 'Services other than education that people pay for, like dorms, dining, parking, etc. At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big.',
    giftData : 'Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem.',
  }

  function getData() {
    let medicalValue = document.getElementById("MedicalCenterInput").value; 
    medicalValue = check_for_Null(medicalValue); 
    let studentValue = document.getElementById("StudentFeesInput").value;
    studentValue = check_for_Null(studentValue);    
    let californiaValue = document.getElementById("CaliforniaInput").value;
    californiaValue = check_for_Null(californiaValue);
    let tuitionValue = document.getElementById("TuitionInput").value;
    tuitionValue = check_for_Null(tuitionValue);
    let researchValue = document.getElementById("ResearchInput").value;
    researchValue = check_for_Null(researchValue);
    let pellGrantValue = document.getElementById("PellGrantInput").value;
    pellGrantValue = check_for_Null(pellGrantValue);
    let noneduValue = document.getElementById("NoneduInput").value;
    noneduValue = check_for_Null(noneduValue);
    let giftValue = document.getElementById("GiftInput").value;
    giftValue = check_for_Null(giftValue); 

    let newData = [ 
    { name: "Medical Center", value: medicalValue, color: "#F0BF00" }, 
    { name: "Student Fees", value: studentValue, color: "#F6E50E" }, 
    { name: "State of California", value: californiaValue, color: "#FFF688" }, 
    { name: "Tuition", value: tuitionValue, color: "#5F63EC" }, 
    { name: "Research Grants and Contracts", value: researchValue, color: "#71A8FF" }, 
    { name: "Pell Grants", value: pellGrantValue, color: "#0F7AB4" }, 
    { name: "Non-educational Services", value: noneduValue, color: "#D4E4FF" }, 
    { name: "Gifts, Endowments, Interest, Etc.", value: giftValue, color: "#bdbdbd" } 
    ]; 

    let total = medicalValue + studentValue + californiaValue + tuitionValue + researchValue + pellGrantValue + noneduValue + giftValue; 

    let totalText = document.getElementById("RevenueTotal"); 
    totalText.value = total;
    totalText.readOnly = true; 

    return newData; 
  }

  
  function check_for_Null(data) {
    let result = ((data == "") ? 0 : (Number(data))); 
    return result; 
  }
 
  function updatePieChart() {
    let newData = getData(); 
    updateChart(newData); 
  }


  return (
    <div>
      <div className='componentTitle'>
        <span>UC Davis Revenue</span>
      </div> 
    
      <div id='RevenueContent'>
        <PieChart name="RevenuePieChart" data={userRevenueData} />

        <div className='inputTitle'>
          <span>Function</span>
          <span>Percentage (%)</span>
        </div>

        <InputPieChart name="MedicalCenterInput" label="Medical Center" color="#F0BF00" callback={updatePieChart} tooltip={toolTipRevenue.medicalCenterData}/>

        <InputPieChart name="StudentFeesInput" label="Student Fees"
        color="#F6E50E" callback={updatePieChart} tooltip={toolTipRevenue.studentFeesData}/>

        <InputPieChart name="CaliforniaInput" label="State of California" color="#FFF688" callback={updatePieChart} tooltip={toolTipRevenue.californiaData}/>

        <InputPieChart name="TuitionInput" label="Tuition" color="#5F63EC" callback={updatePieChart} tooltip={toolTipRevenue.tuitionData}/>

        <InputPieChart name="ResearchInput" label="Research Grants and Contracts" color="#71A8FF" callback={updatePieChart} tooltip={toolTipRevenue.researchData}/>

        <InputPieChart name="PellGrantInput" label="Pell Grants" color="#0F7AB4" callback={updatePieChart} tooltip={toolTipRevenue.pellGrantData}/>

        <InputPieChart name="NoneduInput" label="Non-educational Services" color="#D4E4FF" callback={updatePieChart} tooltip={toolTipRevenue.noneduData}/>

        <InputPieChart name="GiftInput" label="Gifts, Endowments, Interest, Etc." color="#bdbdbd" callback={updatePieChart} tooltip={toolTipRevenue.giftData}/>

        <div className="TotalWrapper"> 
          <span>Total (%)</span> <input className='TotalPercentage'  id="RevenueTotal" /> 
        </div>
      </div>
      
      <div className='buttonWrapper'>
        <button className="whiteButton" id="NextButton" onClick={function() {
          nextPageCallback(); 
        }}>Next</button>
      </div>

    </div>
  ) 

}

export default Revenue; 
